### PR TITLE
feat(icon): sorting icon updated

### PR DESCRIPTION
**Pull request by AykutSarac**
Added sort icon

### CODE REVIEW

**Comment by muratcorlu** [comment]
Please add it regarding to this document: https://trendyol.github.io/baklava/?path=/docs/design-system-icons-adding-new-icons--page

**Comment by AykutSarac** [comment]
> Please add it regarding to this document: https://trendyol.github.io/baklava/?path=/docs/design-system-icons-adding-new-icons--page

Done.

**Comment by muratcorlu** [comment]
@buseselvi we already have `sorting` icon. Do we need both?

**Review by muratcorlu — APPROVED** [review]

**Comment by buseselvi** [comment]
> Details

Can we add the icon I added to this comment? The one that you added is still visible on the storybook. @AykutSarac

**Pull request merged**
