### PR TITLE
feat(select): implement select all

### LINKED ISSUE #520: 'Select All' for Select Component

### PR DESCRIPTION
**Pull request by ogunb**
Closes #520

### CODE REVIEW

**Comment by leventozen** [comment]
Hey @ogunb, have you had the opportunity to check the performance and usability with a significantly large number of options? I previously commented on this issue in our discussion about the select component problem we experienced more recently. You can find my comment in another PR [here](https://github.com/Trendyol/baklava/pull/743#pullrequestreview-1744760447).

**Comment by ogunb** [comment]
1000 items:
Screenshot 2023-12-06 at 12 38 22

I don't think we need any big refactors in this task.

Feel free to suggest improvements though.

---

Also I realized clear all button removes disabled options. Is this intended? Should it stay that way? @buseselvi

**Comment by buseselvi** [comment]
@ogunb If there is a selected disabled option, clear all shouldn't clear them. Can we fix this here? Thank you for noticing.  🙏🏻

**Comment by leventozen** [comment]
Thank you for sharing the 

> Sorry for the late reply, haven't had much time. Here 1000 items: Screenshot 2023-12-06 at 12 38 22
> 
> I don't think we need any big refactors in this task.
> 
> Feel free to suggest improvements though.
> 
> Also I realized clear all button removes disabled options. Is this intended? Should it stay that way? @buseselvi

Looks good imo but let's add one more check in a project. Since we don't have any demo projects on hand right now, we can ask for @AykutSarac to test it in his existing project before merging.

**Review by leventozen — APPROVED** [review]

**Review by AykutSarac — APPROVED** [review]

**Review by fatihhayri — APPROVED** [review]

**Comment by AykutSarac** [comment]
> Looks good imo but let's add one more check. Since we don't have any demo projects on hand right now, we can ask for @AykutSarac to test it in his existing project before merging.

Works fine at our project.

**Comment by buseselvi** [comment]
Good job! 🚀  I have a few notes:
- Can we make the "Select All" title the same font size as other titles in Storybook?
- And I think it would be good to add another example to Storybook without the disabled option.
- Also, yesterday at the meeting we noticed a small bug, when we clicked twice to select all, the checkbox changes like in the image below, can we fix it? 🙏🏻 @ogunb 

image

**Review by buseselvi — APPROVED** [review]

**Pull request merged**
