### PR TITLE
chore(deps): support node v18

### LINKED ISSUE #361: Node 18 support
Currently some parts of the Baklava development environment doesn't work with node 18. Since [Node 18 is the new LTS version](https://nodejs.org/en/blog/release/v18.12.0/), this needs to be fixed.

### PR DESCRIPTION
**Pull request by AykutSarac**
It worked fine on my end but I recommend testing locally.
Closes #361

### CODE REVIEW

**Comment by muratcorlu** [comment]
I know why the pipeline fails: #173 We need to find the proper way of accepting PRs from forks.

**Comment by muratcorlu** [comment]
As far as I see, [storybook v6 doesn’t support node v18](https://github.com/storybookjs/storybook/issues/16555) without [disabling new openssl provider](https://github.com/storybookjs/storybook/issues/16555#issuecomment-1156436628) which is not a great solution.

I think we should consider fixing this together with #522

**Comment by muratcorlu** [comment]
Yeah, I think upgrading to v7 will need a bigger re-organization of our storybook files. Let's connect on that.

**Comment by muratcorlu** [comment]
With MDX2, [they deprecated writing inline stories](https://storybook.js.org/docs/react/migration-guide#storiesmdx-to-mdxcsf) in MDX file. But maybe we can keep them for while if it works. I'll have a look at the branch.

**Comment by muratcorlu** [comment]
I decided to separate tasks by first fixing storybook upgrade (which already works well with both Node 16 and 18) then returning back to node 18 issue. Let's first merge #540 and return back to this. @AykutSarac 

PS: Once we got everything running in node 18 on local, we also need to check our pipeline config, because some of our jobs are forced to use node v16 now.

**Comment by AykutSarac** [comment]
@muratcorlu what do you think about replacing npm with yarn in this PR?

**Review by muratcorlu — APPROVED** [review]

**Pull request merged**
