### PR TITLE
feat(select): render remove button on non required selects

### PR DESCRIPTION
**Pull request by ogunb**
This pull request adds remove button for optional single selects.
Fixes: https://github.com/Trendyol/baklava/issues/608

### CODE REVIEW

**Comment by muratcorlu** [comment]
We need to add `required` to select in the pagination component. Otherwise, clear button will break it.

**Comment by muratcorlu** [comment]
I'm not sure but maybe we need to consider this as a breaking change. 🤔

**Comment by ogunb** [comment]
Although we expect users to have the required prop, some may not. Our implementation and behavior remain consistent and user-friendly. However, it could be seen as a breaking change given the situation. How should we proceed? Should we introduce a temporary boolean like "clearable" or postpone this development?

**Comment by muratcorlu** [comment]
I think we can take that action. The risk looks very low. If some developers use non-required select with a preselected value and don't want to check if the value is set, the only thing they need to do is to add `required` attribute, which really makes sense.

**Review by muratcorlu — APPROVED** [review]

**Review by buseselvi — APPROVED** [review]

**Pull request merged**
