### PR TITLE
feat(input): add attribute for remove icon

### PR DESCRIPTION
**Pull request by Enes5519**
I want to add my custom icon with position: absolute. So I need this attribute.
resim

### CODE REVIEW

**Comment by Enes5519** [comment]
Fixes #627

**Comment by muratcorlu** [comment]
Since it seems you need this functionality just for repositioning the error icon, do you still need this, when we have #643?

**Comment by Enes5519** [comment]
I want to put an icon with a tooltip. That's why I don't want it to be mixed with the normal icon.

**Review by erbilnas — CHANGES_REQUESTED** [review]
@ogunb's last commit  #649 affects here, so this needs to be refactored accordingly

**Comment by ogunb** [comment]
After merging #649 would we still need this attribute? 

I believe, we can solve the problem here with slot icon and some margin. And If we want to remove the default icon anyway we can just provide an empty slot.

**Comment by muratcorlu** [comment]
@Enes5519 can we close with in favor of #649 ?

**Comment by muratcorlu** [comment]
Closing this. Please reopen if you still find this relevant. @Enes5519

**Pull request closed without merging**
