### PR TITLE
fix(pagination): accessibility improvements

### LINKED ISSUE #293: Accessibility improvements on Pagination component
- [ ] Pagination component should be usable with keyboard.
- [ ] Pagination component should use related `aria-` attributes.

Some helpful information: https://www.magentaa11y.com/checklist-web/pagination/

### PR DESCRIPTION
**Pull request by pratikgaloria**
fixes #293

### CODE REVIEW

**Comment by olkeoguz** [comment]
The accessibility works well. But since we currently don't have any margins between the page items, this causes an overlap. @buseselvi @muratcorlu @pratikgaloria 

image

**Review by olkeoguz — COMMENTED** [review]
The accessibility works well. But since we currently don't have any margins between the page items, this causes an overlap. @buseselvi @muratcorlu @pratikgaloria 

image

**Comment by olkeoguz** [comment]
> > The accessibility works well. But since we currently don't have any margins between the page items, this causes an overlap. @buseselvi @muratcorlu @pratikgaloria
> > image
> 
> @olkeoguz yes I have already dropped a message to @buseselvi regarding the same, and we can easily address it by introducing a gap between items, I think `8px` would be fine but still Buse can confirm the value and I will fix it accordingly.

Okey then, I'll approve it afterwards. Thank you 👍

**Comment by buseselvi** [comment]
Hello, can we give them 4px padding and have a look? @pratikgaloria @olkeoguz

**Comment by pratikgaloria** [comment]
@buseselvi it looks like below with 4px gap:
image

please confirm.

**Comment by buseselvi** [comment]
@pratikgaloria we can fix it to 4px, thank you 🙏🏻

**Comment by pratikgaloria** [comment]
@olkeoguz @buseselvi @muratcorlu the gap between numbers is now set to 4px.

**Review by olkeoguz — APPROVED** [review]

**Review by muratcorlu — APPROVED** [review]

**Pull request merged**
