### PR TITLE
feat(icon): add type support for icon name

### PR DESCRIPTION
**Pull request by AykutSarac**
This PR adds type support for icon name, this will bring type support for projects using TypeScript and help us potentially avoid errors in future.

### CODE REVIEW

**Comment by muratcorlu** [comment]
To avoid breaking changes, we need to find a way to work this with multiple icon libraries which we want to have soon: #525

**Comment by AykutSarac** [comment]
@muratcorlu Is there a plan to seperate icon lib to a new package or can we bring type support for icons?

**Comment by muratcorlu** [comment]
Yes, we are planning to exclude icons to a separate package: https://github.com/trendyol/baklava-icons

**Comment by muratcorlu** [comment]
Closing this for now in favor of #656

**Pull request closed without merging**
