### PR TITLE
fix(button)!: button attributes refactored

### PR DESCRIPTION
**Pull request by muratcorlu**
**This is a BREAKING CHANGE**

Currently we use boolean attributes for button variants (`primary`, `secondary`, `success`, `danger`) and types (`contained`, `outline`, `text`). In the beginning we thought this is easier to write but currently I see that this is conflicting with the approach how we use boolean attributes in other components and how we really should use them. Boolean attributes should not rely on other attributes. But now we are technically allowed to write `<bl-button primary secondary>` and in this case result relies on our CSS specifity. And this type of writing does give the feeling that it's possible.

I think we need to fix this as soon as possible to not make confusion for new comers.

This PR converts boolean variants to a more standart `variant` attribute with a default `primary` value again. I picked `fill` attribute value for button types (we use type in storybook) because probably `type` attribute will be needed in near future for using a button as a submitter of a form. Since HTML `button` has `type` I thought we should not use `type` for setting button as `outline` or `text`. Opinions are very welcome.

### CODE REVIEW

**Review by DamlaDemir — APPROVED** [review]

**Comment by DamlaDemir** [comment]
Good job!

**Comment by leventozen** [comment]
Good work! However, I believe using `button-type` is more clear than `fill`. Because in our design system, we are naming `contained`, `outline` and `text` as button types.

**Comment by leventozen** [comment]
After discuss with @DamlaDemir, we think that `type` and `button-type` may confuse people when they need to use them at the same time. We decided to go with `kind` because it is a synonym of `type`.

**Comment by buseselvi** [comment]
can we fix the buttons on the tab component to secondary text button - icon only variant like before?

**Comment by leventozen** [comment]
@buseselvi we fixed it, can you check it again?

**Comment by buseselvi** [comment]
@leventozen buttons look ok 👌  but this time in the hover state tooltip seems to slide down 
image

**Comment by leventozen** [comment]
> @leventozen buttons look ok 👌 but this time in the hover state tooltip seems to slide down image

@buseselvi, this changes are not related to this bug, so we will create another issue. thank you for your attention 🤖

**Review by buseselvi — APPROVED** [review]

**Review by leventozen — APPROVED** [review]

**Pull request merged**
